imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    cache: false

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ FreifunkLinkSinkBundle ]
    #java: /usr/bin/java
    filters:
        less:
          node: /usr/bin/node
          node_paths: [/usr/lib/node_modules]
          apply_to: "\.less$"
        cssrewrite: ~
        compass: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

argentum_feed:
    channels:
        news:
            title: '%feed_title%'
            link: '%feed_link%'
            description: '%feed_desc%'
            pubDate: 'now'
            lastBuildDate: 'now'
            namespaces:
              content: 'http://purl.org/rss/1.0/modules/content/'
              wfw: 'http://wellformedweb.org/CommentAPI/'
              dc: 'http://purl.org/dc/elements/1.1/'
              atom: 'http://www.w3.org/2005/Atom'
              sy: 'http://purl.org/rss/1.0/modules/syndication/'
              slash: 'http://purl.org/rss/1.0/modules/slash/'
              itunes: 'http://www.itunes.com/DTDs/Podcast-1.0.dtd'

services:
    twig.extension.text:
      class: Twig_Extensions_Extension_Text
      tags:
        - { name: twig.extension }