<?php

namespace Freifunk\Bundle\LinkSinkBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function findAllOrderedBySlug()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT t FROM FreifunkLinkSinkBundle:Tag t ORDER BY t.slug ASC'
            )
            ->getResult();
    }
}
